export 'package:alice_store/ui/pages/home_page.dart';
export 'package:alice_store/ui/pages/about_project_page.dart';
export 'package:alice_store/ui/pages/wishlist_page.dart';
export 'package:alice_store/ui/pages/drawer_page.dart';
export 'package:alice_store/ui/pages/shopping_page.dart';
export 'package:alice_store/ui/pages/cart_page.dart';
export 'package:alice_store/ui/pages/product_detail_page.dart';
export 'package:alice_store/ui/pages/no_internet_page.dart';
export 'package:alice_store/ui/pages/similar_products_page.dart';